export const Actions = {
	USER_AUTHENTICATION_SUCCESS: 'USER_AUTHENTICATION_SUCCESS',
	GET_ALL_TITLES_SUCCESS: 'GET_ALL_TITLES_SUCCESS',
	INCREASE_COUNT: 'INCREASE_COUNT',
	RESET_STATE: 'RESET_STATE',
};
